name: macOS

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'JuceLibraryCode/**'
    - 'PluginGenerator/**'
    - 'Plugins/**'
    - 'Resources/**'
    - 'Source/**'
    - 'CMakeLists.txt'
    - 'HelperFunctions.cmake'

jobs:
  build-osx:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: configure
      run: |
        cd Build 
        cmake -G "Xcode" ..
    - name: build
      run: |
        cd Build 
        xcodebuild -configuration Release 
#    - name: test
#      run: cd build && ctest
    - name: deploy_dev
      if: github.ref == 'refs/heads/development-juce8'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
      run: |
        zipfile=open-ephys-v1.0.0-dev-mac.zip
        cd Build/Release
        mkdir open-ephys
        mv open-ephys.app/ open-ephys
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$artifactoryApiKey"
        curl -H $user_info -T $zipfile "https://openephysgui.jfrog.io/artifactory/1.0.0-dev/mac/$zipfile"
    - name: deploy_preview
      if: github.ref_type == 'tag'
      env:
        artifactoryApiKey: ${{ secrets.artifactoryApiKey }}
      run: |
        gui_ver=$(git describe --tags $(git rev-list --tags --max-count=1))
        zipfile=open-ephys-${gui_ver}-mac.zip
        cd Build/Release
        mkdir open-ephys
        mv open-ephys.app/ open-ephys
        zip -r $zipfile open-ephys
        user_info="X-JFrog-Art-Api:$artifactoryApiKey"
        curl -H $user_info -T $zipfile "https://openephysgui.jfrog.io/artifactory/1.0.0-pre/mac/$zipfile"
